export const users = [
  {
    id: 1,
    name: "John Doe",
    country: "USA",
    college: "Harvard University",
    income: "$75,000",
    hobby: "Photography",
  },
  {
    id: 2,
    name: "Emily Smith",
    country: "Canada",
    college: "University of Toronto",
    income: "$68,000",
    hobby: "Traveling",
  },
  {
    id: 3,
    name: "Michael Johnson",
    country: "UK",
    college: "Oxford University",
    income: "$80,000",
    hobby: "Cooking",
  },
  {
    id: 4,
    name: "Sophia Williams",
    country: "Australia",
    college: "University of Sydney",
    income: "$72,000",
    hobby: "Painting",
  },
  {
    id: 5,
    name: "Daniel Martinez",
    country: "Spain",
    college: "University of Barcelona",
    income: "$65,000",
    hobby: "Cycling",
  },
  {
    id: 6,
    name: "Olivia Brown",
    country: "Germany",
    college: "University of Munich",
    income: "$78,000",
    hobby: "Reading",
  },
  {
    id: 7,
    name: "Liam Taylor",
    country: "France",
    college: "Sorbonne University",
    income: "$82,000",
    hobby: "Guitar",
  },
  {
    id: 8,
    name: "Emma Wilson",
    country: "Italy",
    college: "University of Rome",
    income: "$70,000",
    hobby: "Dancing",
  },
  {
    id: 9,
    name: "Noah Anderson",
    country: "Netherlands",
    college: "University of Amsterdam",
    income: "$76,000",
    hobby: "Chess",
  },
  {
    id: 10,
    name: "Ava Thompson",
    country: "Sweden",
    college: "Lund University",
    income: "$74,000",
    hobby: "Yoga",
  },
  {
    id: 11,
    name: "Ethan White",
    country: "Brazil",
    college: "University of São Paulo",
    income: "$69,000",
    hobby: "Surfing",
  },
  {
    id: 12,
    name: "Isabella Garcia",
    country: "Mexico",
    college: "National Autonomous University of Mexico",
    income: "$63,000",
    hobby: "Baking",
  },
  {
    id: 13,
    name: "Mason Clark",
    country: "India",
    college: "IIT Bombay",
    income: "$85,000",
    hobby: "Cricket",
  },
  {
    id: 14,
    name: "Mia Rodriguez",
    country: "Japan",
    college: "University of Tokyo",
    income: "$77,000",
    hobby: "Calligraphy",
  },
  {
    id: 15,
    name: "James Lee",
    country: "South Korea",
    college: "Seoul National University",
    income: "$79,000",
    hobby: "K-pop Dancing",
  },
];

export const companies = [
  {
    id: 101,
    name: "Tech Solutions Inc.",
    location: "San Francisco, USA",
    revenue: "$500M",
    stockPrice: "$350",
    international: "Yes",
    offices: 15,
    employees: "10,000+",
  },
  {
    id: 102,
    name: "Green Energy Ltd.",
    location: "Berlin, Germany",
    revenue: "$300M",
    stockPrice: "$220",
    international: "No",
    offices: 10,
    employees: "7,500",
  },
  {
    id: 103,
    name: "FinTech Corp.",
    location: "London, UK",
    revenue: "$750M",
    stockPrice: "$500",
    international: "Yes",
    offices: 20,
    employees: "12,000",
  },
  {
    id: 104,
    name: "AI Innovations",
    location: "Tokyo, Japan",
    revenue: "$1.2B",
    stockPrice: "$650",
    international: "Yes",
    offices: 25,
    employees: "15,000",
  },
  {
    id: 105,
    name: "CloudNet Systems",
    location: "Sydney, Australia",
    revenue: "$900M",
    stockPrice: "$430",
    international: "Yes",
    offices: 12,
    employees: "8,000",
  },
  {
    id: 106,
    name: "HealthTech Solutions",
    location: "Toronto, Canada",
    revenue: "$550M",
    stockPrice: "$280",
    international: "No",
    offices: 8,
    employees: "6,500",
  },
  {
    id: 107,
    name: "E-Commerce Hub",
    location: "Paris, France",
    revenue: "$1.5B",
    stockPrice: "$700",
    international: "Yes",
    offices: 30,
    employees: "20,000",
  },
  {
    id: 108,
    name: "CyberShield Security",
    location: "Seoul, South Korea",
    revenue: "$650M",
    stockPrice: "$340",
    international: "Yes",
    offices: 18,
    employees: "11,000",
  },
  {
    id: 109,
    name: "AutoDrive Technologies",
    location: "Detroit, USA",
    revenue: "$2.1B",
    stockPrice: "$890",
    international: "Yes",
    offices: 40,
    employees: "30,000",
  },
  {
    id: 110,
    name: "EduTech Solutions",
    location: "New Delhi, India",
    revenue: "$300M",
    stockPrice: "$210",
    international: "No",
    offices: 14,
    employees: "9,500",
  },
  {
    id: 111,
    name: "AgriTech Innovations",
    location: "São Paulo, Brazil",
    revenue: "$450M",
    stockPrice: "$290",
    international: "Yes",
    offices: 22,
    employees: "13,500",
  },
  {
    id: 112,
    name: "GameVerse Studios",
    location: "Los Angeles, USA",
    revenue: "$1.8B",
    stockPrice: "$750",
    international: "Yes",
    offices: 35,
    employees: "25,000",
  },
  {
    id: 113,
    name: "SmartHome Technologies",
    location: "Amsterdam, Netherlands",
    revenue: "$600M",
    stockPrice: "$370",
    international: "Yes",
    offices: 16,
    employees: "9,000",
  },
  {
    id: 114,
    name: "Blockchain Inc.",
    location: "Singapore",
    revenue: "$1.2B",
    stockPrice: "$620",
    international: "Yes",
    offices: 20,
    employees: "14,500",
  },
  {
    id: 115,
    name: "Quantum Computing Labs",
    location: "Zurich, Switzerland",
    revenue: "$2.5B",
    stockPrice: "$950",
    international: "Yes",
    offices: 50,
    employees: "40,000",
  },
];
