export default users = [
    {
      id: 1,
      name: "John Doe",
      country: "USA",
      college: "Harvard University",
      income: "$75,000",
      hobby: "Photography",
    },
    {
      id: 2,
      name: "Emily Smith",
      country: "Canada",
      college: "University of Toronto",
      income: "$68,000",
      hobby: "Traveling",
    },
    {
      id: 3,
      name: "Michael Johnson",
      country: "UK",
      college: "Oxford University",
      income: "$80,000",
      hobby: "Cooking",
    },
    {
      id: 4,
      name: "Sophia Williams",
      country: "Australia",
      college: "University of Sydney",
      income: "$72,000",
      hobby: "Painting",
    },
    {
      id: 5,
      name: "Daniel Martinez",
      country: "Spain",
      college: "University of Barcelona",
      income: "$65,000",
      hobby: "Cycling",
    },
    {
      id: 6,
      name: "Olivia Brown",
      country: "Germany",
      college: "University of Munich",
      income: "$78,000",
      hobby: "Reading",
    },
    {
      id: 7,
      name: "Liam Taylor",
      country: "France",
      college: "Sorbonne University",
      income: "$82,000",
      hobby: "Guitar",
    },
    {
      id: 8,
      name: "Emma Wilson",
      country: "Italy",
      college: "University of Rome",
      income: "$70,000",
      hobby: "Dancing",
    },
    {
      id: 9,
      name: "Noah Anderson",
      country: "Netherlands",
      college: "University of Amsterdam",
      income: "$76,000",
      hobby: "Chess",
    },
    {
      id: 10,
      name: "Ava Thompson",
      country: "Sweden",
      college: "Lund University",
      income: "$74,000",
      hobby: "Yoga",
    },
    {
      id: 11,
      name: "Ethan White",
      country: "Brazil",
      college: "University of São Paulo",
      income: "$69,000",
      hobby: "Surfing",
    },
    {
      id: 12,
      name: "Isabella Garcia",
      country: "Mexico",
      college: "National Autonomous University of Mexico",
      income: "$63,000",
      hobby: "Baking",
    },
    {
      id: 13,
      name: "Mason Clark",
      country: "India",
      college: "IIT Bombay",
      income: "$85,000",
      hobby: "Cricket",
    },
    {
      id: 14,
      name: "Mia Rodriguez",
      country: "Japan",
      college: "University of Tokyo",
      income: "$77,000",
      hobby: "Calligraphy",
    },
    {
      id: 15,
      name: "James Lee",
      country: "South Korea",
      college: "Seoul National University",
      income: "$79,000",
      hobby: "K-pop Dancing",
    },
  ];

  